export const BRANDS = ["Apple", "Samsung", "Google", "OnePlus", "Other"] as const;
export type Brand = (typeof BRANDS)[number];

export const MODELS: Record<Brand, string[]> = {
  Apple: [
    "iPhone 16 Pro Max",
    "iPhone 16 Pro",
    "iPhone 16 Plus",
    "iPhone 16",
    "iPhone 15 Pro Max",
    "iPhone 15 Pro",
    "iPhone 15 Plus",
    "iPhone 15",
    "iPhone 14 Pro Max",
    "iPhone 14 Pro",
    "iPhone 14 Plus",
    "iPhone 14",
    "iPhone 13 Pro Max",
    "iPhone 13 Pro",
    "iPhone 13",
    "iPhone 13 mini",
    "iPhone 12 Pro Max",
    "iPhone 12 Pro",
    "iPhone 12",
    "iPhone 12 mini",
    "iPhone 11 Pro Max",
    "iPhone 11 Pro",
    "iPhone 11",
    "iPhone SE (3rd gen)",
    "Other Apple",
  ],
  Samsung: [
    "Galaxy S25 Ultra",
    "Galaxy S25+",
    "Galaxy S25",
    "Galaxy S24 Ultra",
    "Galaxy S24+",
    "Galaxy S24",
    "Galaxy S23 Ultra",
    "Galaxy S23+",
    "Galaxy S23",
    "Galaxy S22 Ultra",
    "Galaxy S22+",
    "Galaxy S22",
    "Galaxy Z Fold 6",
    "Galaxy Z Flip 6",
    "Galaxy Z Fold 5",
    "Galaxy Z Flip 5",
    "Galaxy Note 20 Ultra",
    "Other Samsung",
  ],
  Google: [
    "Pixel 9 Pro XL",
    "Pixel 9 Pro",
    "Pixel 9",
    "Pixel 8 Pro",
    "Pixel 8",
    "Pixel 7 Pro",
    "Pixel 7",
    "Pixel 6 Pro",
    "Pixel 6",
    "Other Pixel",
  ],
  OnePlus: ["OnePlus 12", "OnePlus 11", "OnePlus 10 Pro", "Other OnePlus"],
  Other: ["Other Device"],
};

export const CONDITIONS = [
  { value: "excellent", label: "Excellent", hint: "Like new, no scratches" },
  { value: "good", label: "Good", hint: "Minor wear, fully working" },
  { value: "fair", label: "Fair", hint: "Visible wear, fully working" },
  { value: "damaged", label: "Damaged", hint: "Cracks, dents, or faults" },
] as const;

export const ISSUES = [
  "Cracked screen",
  "Cracked back",
  "Battery issue",
  "Water damage",
  "Won't turn on",
  "Face ID / Touch ID not working",
  "Camera issue",
  "Speaker / mic issue",
  "Charging port issue",
  "Locked to carrier",
  "iCloud / Google locked",
] as const;
